name: Create New Release
on: workflow_dispatch

jobs:
  standard-version:
    name: "Run standard-version"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure committer
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Bump version
        uses: qzb/standard-version-action@v1.0.5
      
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true

  create-release:
    needs: standard-version
    name: "Create Github Release"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Build & test"
        run: yarn build

      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: "Create Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.previoustag.outputs.tag }}
          prerelease: false
          files: |
            LICENSE
            CHANGELOG.md
            dist

  # publish-npm:
  #   needs: create-release
  #   name: "Publish on NPM Registry"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Setup Node
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: "16.x"
  #         registry-url: "https://registry.npmjs.org"

  #     - name: Install dependencies and build 🔧
  #       run: yarn install && yarn build

  #     - name: Publish package on NPM 📦
  #       run: yarn publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
